#!/bin/bash

# Wispro Bandwidth Management Unit
WISPRO_URL="https://www.cloud.wispro.co"
FOR_BMU_VERSION="0.2.0"
BMU_NGINX_VERSION="1.2"
BMU_DNSMASQ_VERSION="1.3"
FREERADIUS_VERSION="1.2"
BMU_POSTGRESQL_VERSION="1.0"
VOLUMES_PATH=/usr/src/app
DAEMONS_TO_CHECK_AFTER_UPGRADE="bmud bmud_daemon_check_link bmud_daemon_cloud_consumer bmud_daemon_cloud_sync bmud_daemon_contract_notifications"
WISPRO_SCRIPT_FILE=${BASH_SOURCE}
LOG_PATH=/usr/src/app/log

# We store lines and columns to tell docker later about console size
LINES=$(stty size| cut -d" " -f1)
COLUMNS=$(stty size| cut -d" " -f2)

# Docker host dirs as volumes
VOLUMES="-v ${VOLUMES_PATH}/tmp:/usr/src/app/tmp"
VOLUMES="${VOLUMES} -v ${VOLUMES_PATH}/log:/usr/src/app/log"
VOLUMES="${VOLUMES} -v ${VOLUMES_PATH}/public/assets:/usr/src/app/public/assets"  # public assets
VOLUMES="${VOLUMES} -v ${VOLUMES_PATH}/data:/usr/src/app/data"
VOLUMES="${VOLUMES} -v ${VOLUMES_PATH}/etc:/usr/src/app/etc"
VOLUMES="${VOLUMES} -v ${VOLUMES_PATH}/scripts:/usr/src/app/scripts"
VOLUMES="${VOLUMES} -v /etc/dhcp:/etc/dhcp"
VOLUMES="${VOLUMES} -v /etc/ppp:/etc/ppp"


### ================== NGINX =====================
NGINX=nginx
NGINX_VOLUMES="-v ${LOG_PATH}/nginx:/var/log/nginx" # Logs
NGINX_VOLUMES="$NGINX_VOLUMES -v ${VOLUMES_PATH}/public/assets:/app/public/assets"  # public assets

run_nginx() {
  if container_exists $NGINX; then
    docker start $NGINX
  else
    local extra_params="--log-opt max-size=1m --log-opt max-file=3 --restart=unless-stopped"
    extra_params="$extra_params -d --network host --name $NGINX -h $NGINX -p 80:80 -p 443:443 $NGINX_VOLUMES"

    docker run $extra_params wispro/bmu_nginx:${BMU_NGINX_VERSION}
  fi
}

stop_nginx() {
  docker stop $NGINX
}

start_nginx() {
  if is_running $NGINX; then
    stop_nginx
  fi

  run_nginx
}

### ================== FREERADIUS =====================
FREERADIUS=freeradius
FREERADIUS_VOLUMES="-v /usr/src/app/data/clients.conf:/etc/raddb/clients.conf"
FREERADIUS_VOLUMES="$FREERADIUS_VOLUMES -v /usr/src/app/data/users:/etc/raddb/users"  # public assets

start_freeradius() {
  if ! is_running $FREERADIUS; then
    if container_exists $FREERADIUS; then
      docker start $FREERADIUS
    else
      echo "Initializing new docker container with version wispro/bmu_freeradius:${FREERADIUS_VERSION}"
      local extra_params="--log-opt max-size=1m --log-opt max-file=3 --restart=unless-stopped"
      extra_params="$extra_params -d --network host --name $FREERADIUS -h $FREERADIUS -p 1812:1812/udp  -p 1813:1813 -p 18120:18120 $FREERADIUS_VOLUMES wispro/bmu_freeradius:${FREERADIUS_VERSION}"
      docker run $extra_params
    fi

    return $?
    #echo $(docker inspect -f '{{ .State.Pid }}' $name) > $WISPRO_SERVER_PIDFILE
  fi
}

stop_freeradius() {
  docker stop $FREERADIUS
}

### ================== DNSMASQ =====================
DNSMASQ=dnsmasq
#DNSMASQ_VOLUMES="-v /usr/src/app/data/dnsmasq.conf:/etc/dnsmasq.conf"
DNSMASQ_VOLUMES="$DNSMASQ_VOLUMES -v /usr/src/app/data/dnsmasq.d/:/etc/dnsmasq.d/"
DNSMASQ_VOLUMES="$DNSMASQ_VOLUMES -v /etc/resolv.conf:/etc/resolv.conf"
DNSMASQ_VOLUMES="$DNSMASQ_VOLUMES -v /usr/src/app/data/dnsmasq.wispro/:/etc/dnsmasq.wispro/"

start_dnsmasq() {
  if ! is_running $DNSMASQ; then
    if container_exists $DNSMASQ; then
      docker start $DNSMASQ
    else
      echo "Stop local dnsmasq"
      if [[ -x /usr/sbin/dnsmasq ]]; then
        service dnsmasq stop
        apk del dnsmasq
      fi
      echo "Initializing new docker container with version wispro/dnsmasq"
      local extra_params="--log-opt max-size=1m --log-opt max-file=3 --restart=unless-stopped"
      extra_params="$extra_params -d --network host --name $DNSMASQ -h $DNSMASQ -p 53:53/tcp -p 53:53/udp --cap-add=NET_ADMIN $DNSMASQ_VOLUMES"
      docker run $extra_params wispro/bmu_dnsmasq:${BMU_DNSMASQ_VERSION}
    fi
    return $?
    #echo $(docker inspect -f '{{ .State.Pid }}' $name) > $WISPRO_SERVER_PIDFILE
  fi
}

stop_dnsmasq() {
  docker stop $DNSMASQ
}

### ================== POSTGRESQL =====================
POSTGRESQL=bmu_postgresql
POSTGRESQL_VOLUMES="-v ${LOG_PATH}/postgresql:/var/log/postgresql" # Logs
POSTGRESQL_VOLUMES="$POSTGRESQL_VOLUMES -v ${VOLUMES_PATH}/data/postgresql:/var/lib/postgresql/data:rw"

run_postgresql() {
  if container_exists $POSTGRESQL; then
    docker start $POSTGRESQL
  else
    local extra_params="--log-opt max-size=1m --log-opt max-file=3 --restart=unless-stopped"
    extra_params="$extra_params -d --network host --name $POSTGRESQL -h $POSTGRESQL -p 5432:5432 $POSTGRESQL_VOLUMES"

    docker run $extra_params wispro/bmu_postgresql:${BMU_POSTGRESQL_VERSION}
  fi
}

stop_postgresql() {
  docker stop $POSTGRESQL
}

start_postgresql() {
  if is_running $POSTGRESQL; then
    echo 'running...'
  else
    echo "waking up postgres"
    run_postgresql
  fi
}



### ================== COMMON FUNCTIONS =====================
is_running(){
  if docker top $1 &>/dev/null; then
    return 0
  else
    return 1
  fi
}
container_exists(){
  local container_name=$1
  if [[ $(docker ps -a -f "name=$container_name\$" --format '{{.Names}}') == $container_name ]]; then
    return 0
  else
    return 1
  fi
}
daemon_is_running (){
  local daemon=$1
  for daemon_running in $daemons_running; do
    [[ $daemon_to_check == $daemon_running ]] && return 0
  done
  return 1
}
daemons_are_running(){
  local found=0
  daemons_running=$(docker top wispro-daemon | grep ruby | awk '{print $5}')
  for daemon_to_check in $DAEMONS_TO_CHECK_AFTER_UPGRADE; do
    daemon_is_running daemon_to_check || return 1
  done
  return 0
}

stop(){
  local stop_name=wispro-${1}
  #if is_running $name; then
    docker stop $stop_name
    if [[ "$stop_name" == "wispro-server" ]]; then
      stop_nginx
    fi
  #fi
}
start(){
  local start_name=$1 extra_args="" rsync_with_developer_file=/usr/src/app/tmp/.rsync_with_developer
  if [[ "${BASH_ARGV[0]}" == "sync" ]]; then
    touch $rsync_with_developer_file
  else
    [[ -r $rsync_with_developer_file ]] && rm -f $rsync_with_developer_file
  fi
  if [[ $start_name == "server" ]];then
    extra_args="-p 3000:3000"
  fi

  full_name=wispro-${start_name}

  start_postgresql

  if ! is_running $full_name; then
    if container_exists $full_name; then
      opts="start $full_name"
    else
      if [[ -z "${VERSION}" ]]; then
        echo "VERSION= is unset, please run: "
        echo "# VERSION=version_number wispro start"
        exit 1
      else
        echo "Initializing new docker container with version wispro/bmu:${VERSION}"
        opts="run --log-opt max-size=1m --log-opt max-file=3 --restart=unless-stopped"
        opts="$opts -d ${extra_args} ${VOLUMES} --name $full_name -h $full_name wispro/bmu:${VERSION} /usr/src/app/bin/docker-cmd-$start_name.sh"
      fi
    fi
    docker $opts

    if [[ $full_name == "wispro-server" ]]; then
      start_nginx
    fi

    start_dnsmasq

    return $?
    #echo $(docker inspect -f '{{ .State.Pid }}' $name) > $WISPRO_SERVER_PIDFILE
  fi
}


### ================== COMMAND ARGUMENTS =====================
case $1 in
check)
  ;;
start)
  if [[ -n "${2}" ]];then
    case $2 in
    $FREERADIUS)
      start_freeradius;;
    $DNSMASQ)
      start_dnsmasq;;
    $POSTGRESQL)
      start_postgresql;;
    *)
      start ${2};;
    esac
    # if [[ $2 == $FREERADIUS ]];then
    #   start_freeradius
    # else
    #   start ${2}
    # fi
  else
    start server
    start daemon
  fi
  ;;
stop)
  if [[ -n "${2}" ]];then
    case $2 in
    $FREERADIUS)
      stop_freeradius;;
    $DNSMASQ)
      stop_dnsmasq;;
    $POSTGRESQL)
      stop_postgresql;;
    *)
      stop ${2};;
    esac
    # if [[ $2 == $FREERADIUS ]];then
    #   stop_freeradius
    # else
    #   stop ${2}
    # fi
  else
    stop server
    stop daemon
  fi
  ;;
restart)
  if [[ -n "${2}" ]];then
    case $2 in
      $FREERADIUS)
        stop_freeradius
        start_freeradius;;
      $DNSMASQ)
        stop_dnsmasq
        start_dnsmasq;;
      $POSTGRESQL)
        stop_postgresql
        start_postgresql;;
      *)
        stop ${2}
        start ${2}
    esac
  else
    stop server
    stop daemon
    start server
    start daemon
  fi
  ;;
upgrade)
  set -x
  #TODO trap
  do_exit(){
    if [[ "$1" == "restore_old_version" ]]; then
      restore_old_version
    fi
    echo "Upgrade to version ${new_version} failed."
    exit 1
  }
  restore_old_version(){
    restore_container(){
      restore_container=$1
      if container_exists $restore_container; then
        docker container rm $restore_container
      fi
      docker container rename ${restore_container}-bak $restore_container
    }
    VERSION=$old_version
    stop server
    stop daemon

    restore_container wispro-server
    restore_container wispro-daemon

    start server
    start daemon
  }
  apply_patches(){
    action=$1
    restore=$2
    patch_file=$(mktemp)
    status_code=$(curl -w "%{http_code}" -o $patch_file "${WISPRO_URL}/bmu_versions/${action}?api_token=${api_token}&from=${old_version}&to=${new_version}")
    if [[ "$status_code" == "200" ]]; then
      if [[ "$(/bin/bash $patch_file TEST)" == "OK" ]];then
        cat $patch_file
        if ! /bin/bash $patch_file; then
          do_exit $restore
        fi
      else
        do_exit $restore
      fi
    else
      do_exit $restore
    fi
  }
  download_new_wispro(){
    tmp_script=$(mktemp)
    http_code=$(curl -w '%{http_code}' -L "https://github.com/sequre/wispro_installer/raw/${new_version}/wispro" -o $tmp_script)
    if [[ $? -eq 0 && "${http_code}" = "200" && "$(/bin/bash ${tmp_script} version)" = "${new_version}" ]] && \
      #cp ${WISPRO_SCRIPT_FILE} ${WISPRO_SCRIPT_FILE}.bak && \
      chmod 755 ${tmp_script} && \
      cp $tmp_script ${WISPRO_SCRIPT_FILE}; then
      [ -d ${LOG_PATH} ] || mkdir -p $LOG_PATH
      # Empezamos de nuevo con el upgrade, pero ya tenemos la nueva versión de wispro (el script)
      # que acaba de pisar este mismo script que estamos ejecutando, por eso hacemos exec
      # para asegurarnos de salir del current script y ejectuar el que acabamos de bajar
      exec ${WISPRO_SCRIPT_FILE} upgrade ${new_version}  &>${LOG_PATH}/wispro_upgrade_to_${new_version}
      echo "If you read this message then something had gone seriously WRONG"
    else
      echo "Unable to download and test wispro script with tag: ${new_version}"
    fi
    do_exit
  }
  backup_container(){
    backup_container=$1
    if container_exists $backup_container; then
      if container_exists ${backup_container}-bak; then
        docker container rm ${backup_container}-bak
      fi
      docker container rename ${backup_container} ${backup_container}-bak
    fi
  }
  upgrade_containers(){
    old_bmu_dnsmasq_version=$(docker inspect --format='{{.Config.Image}}' dnsmasq | awk -F: '{print $2}')
    if [[ "$old_bmu_dnsmasq_version" != "$BMU_DNSMASQ_VERSION" ]]; then
      iptables -t nat -I WISPRO_PREROUTING -p udp --dport 53 -j DNAT --to 8.8.8.8
      stop_dnsmasq
      docker container rm dnsmasq
      start_dnsmasq
      sleep 3
      iptables -t nat -D WISPRO_PREROUTING -p udp --dport 53 -j DNAT --to 8.8.8.8
    fi
    if container_exists freeradius;then
      old_bmu_freeradius_version=$(docker inspect --format='{{.Config.Image}}' freeradius | awk -F: '{print $2}')
      if [[ "$old_bmu_freeradius_version" != "$FREERADIUS_VERSION" ]];then
        if is_running freeradius; then
          freeradius_is_running=true
        else
          freeradius_is_running=false
        fi
        if $freeradius_is_running;then
          stop_freeradius
        fi
        docker container rm freeradius
        if $freeradius_is_running;then
          start_freeradius
        fi
      fi
    fi
    old_bmu_nginx_version=$(docker inspect --format='{{.Config.Image}}' nginx  | awk -F: '{print $2}')
    if [[ "$old_bmu_nginx_version" != "$BMU_NGINX_VERSION" ]]; then
      stop_nginx
      docker container rm nginx
      start_nginx
    fi
  }
  new_version=$2
  if [[ "${new_version}" != $FOR_BMU_VERSION ]];then
    download_new_wispro
  fi
  # usamos xargs al final para hacer un simil chomp
  api_token=$(docker exec -t wispro-server /bin/bash -c "rails runner 'puts ServerConfiguration.first.api_token'" | tail -n1 | tr -d '\r')
  if docker pull wispro/bmu:${new_version} && \
     docker pull wispro/bmu_nginx:${BMU_NGINX_VERSION} && \
     docker pull wispro/bmu_freeradius:${FREERADIUS_VERSION} && \
     docker pull wispro/bmu_dnsmasq:${BMU_DNSMASQ_VERSION} && \
     docker pull wispro/bmu_postgresql:${BMU_POSTGRESQL_VERSION}; then

    old_version=$(docker inspect --format='{{.Config.Image}}' wispro-server | awk -F: '{print $2}')
    apply_patches "patches_pre"

    sleep 3 #give time to save bmu_update

    stop server
    stop daemon
    backup_container wispro-server
    backup_container wispro-daemon

    VERSION=$new_version

    start server
    start daemon

    sleep 30
    if is_running wispro-server && is_running wispro-daemon && daemons_are_running; then
      # Check server container with for example an its_alive via http
      apply_patches "patches_post" "restore_old_version"
      upgrade_containers
      exit 0
    else
      restore_old_version
      do_exit
    fi
  else
    do_exit
  fi
  ;;
console)
  docker exec -it --env COLUMNS=$COLUMNS --env LINES=$LINES wispro-server /bin/bash -c "rails c"
  ;;
log)
  tail -n500 -F /usr/src/app/log/application.log
  ;;
apply)
  docker exec -it --env COLUMNS=$COLUMNS --env LINES=$LINES wispro-server /bin/bash -c "rails runner 'ApplyChanges.new.boot'"
  ;;
bash-server)
  docker exec -it --env COLUMNS=$COLUMNS --env LINES=$LINES wispro-server /bin/bash
  ;;
bash-daemon)
  docker exec -it --env COLUMNS=$COLUMNS --env LINES=$LINES wispro-daemon /bin/bash
  ;;
reset)
  echo "Deleting Server/Daemon containers, are you sure?"
  echo "(Pres Ctrl-c to cancel/Enter to continue)"
  read dummy
  VERSION=$(docker inspect --format='{{.Config.Image}}' wispro-server | awk -F: '{print $2}')
  stop server
  stop daemon
  docker container prune -f
  start server
  start daemon
  ;;
top)
  echo
  echo "Wispro Server"
  docker top wispro-server
  echo
  echo "Wispro Daemon"
  docker top wispro-daemon
  echo
  echo "Wispro Nginx"
  docker top nginx
  ;;
# Con esto verifco que este todo ok después de bajar el archivo
version)
  echo $FOR_BMU_VERSION
  ;;
runner)
  random_name=$(date +%s | sha256sum | head -c 32)
  runner_opts="${VOLUMES} --name $random_name wispro/bmu:$FOR_BMU_VERSION"

  echo $runner_opts
  docker run $runner_opts ${@:2}
  exit_code=$?

  sleep 1
  docker rm -f $random_name

  exit $exit_code
  ;;
*)
  echo "error - wrong arguments"
  ;;
esac
