#!/bin/bash
# Wispro Bandwidth Management Unit

VOLUMES_PATH=/usr/src/app
DAEMONS_TO_CHECK_AFTER_UPGRADE="bmud bmud_daemon_check_link bmud_daemon_cloud_consumer bmud_daemon_cloud_sync bmud_daemon_contract_notifications"

# Docker host dirs as volumes
VOLUMES="-v ${VOLUMES_PATH}/tmp:/usr/src/app/tmp"
VOLUMES="${VOLUMES} -v ${VOLUMES_PATH}/log:/usr/src/app/log"
VOLUMES="${VOLUMES} -v ${VOLUMES_PATH}/data:/usr/src/app/data"
VOLUMES="${VOLUMES} -v ${VOLUMES_PATH}/etc:/usr/src/app/etc"
VOLUMES="${VOLUMES} -v ${VOLUMES_PATH}/scripts:/usr/src/app/scripts"

is_running(){
  local name=$1
  if docker top $name &>/dev/null; then
    return 0
  else
    return 1
  fi
}
container_exists(){
  local name=$1
  if [[ $(docker ps -a -f "name=$name\$" --format '{{.Names}}') == $name ]]; then
    return 0
  else
    return 1
  fi
}
daemon_is_running (){
  local daemon=$1
  for daemon_running in $daemons_running; do
    [[ $daemon_to_check == $daemon_running ]] && return 0
  done
  return 1
}
daemons_are_running(){
  local found=0
  daemons_running=$(docker top wispro-daemon | grep ruby | awk '{print $5}')
  for daemon_to_check in $DAEMONS_TO_CHECK_AFTER_UPGRADE; do
    daemon_is_running daemon_to_check || return 1
  done
  return 0
}

stop(){
  local name=wispro-${1}
  #if is_running $name; then
    docker stop $name
  #fi
}
start(){
  local name=$1 extra_args="" rsync_with_developer_file=/usr/src/app/tmp/.rsync_with_developer
  if [[ "${BASH_ARGV[0]}" == "sync" ]]; then
    touch $rsync_with_developer_file
  else
    [[ -r $rsync_with_developer_file ]] && rm -f $rsync_with_developer_file
  fi
  if [[ $name == "server" ]];then
    extra_args="-p 80:3000"
  fi
  full_name=wispro-${name}
  if ! is_running $full_name; then
    if container_exists $full_name; then
      opts="start $full_name"
    else
      if [[ -z "${VERSION}" ]]; then
        echo "VERSION= is unset, please run: "
        echo "# VERSION=version_number wispro start"
        exit 1
      else
        echo "Initializing new docker container with version wispro/bmu:${VERSION}"
        opts="run --log-opt max-size=1m --log-opt max-file=3 --restart=unless-stopped -d ${extra_args} ${VOLUMES} --name $full_name -h $full_name wispro/bmu:${VERSION} /usr/src/app/bin/docker-cmd-$name.sh"
      fi
    fi
    docker $opts
    return $?
    #echo $(docker inspect -f '{{ .State.Pid }}' $name) > $WISPRO_SERVER_PIDFILE
  fi
}
case $1 in
check)
  ;;
start)
  if [[ -n "${2}" ]];then
    start ${2}
  else
    start server
    start daemon
  fi
  ;;
stop)
  if [[ -n "${2}" ]];then
    stop ${2}
  else
    stop server
    stop daemon
  fi
  ;;
restart)
  if [[ -n "${2}" ]];then
    stop ${2}
    start ${2}
  else
    stop server
    stop daemon
    start server
    start daemon
  fi
  ;;
upgrade)
  #TODO trap
  set -x
  old_version=$(docker inspect --format='{{.Config.Image}}' wispro-server | awk -F: '{print $2}')
  new_version=$2
  if docker pull wispro/bmu:${new_version}; then
    sleep 3 #give time to save bmu_update
    stop server
    stop daemon
    db_path=${VOLUMES_PATH}/data/wispro_bmu_production.sqlite3
    #TODO reemplazar bak por el nro de version o algo así para poder volver
    cp $db_path ${db_path}.bak

    if container_exists wispro-server; then
      if container_exists wispro-server-bak; then
        docker container rm wispro-server-bak
      fi
      docker container rename wispro-server wispro-server-bak
    fi
    if container_exists wispro-daemon; then
      if container_exists wispro-daemon-bak; then
        docker container rm wispro-daemon-bak
      fi
      docker container rename wispro-daemon wispro-daemon-bak
    fi
    VERSION=$new_version
    start server
    start daemon
    sleep 30
    if is_running wispro-server && is_running wispro-daemon && daemons_are_running; then
      # Check server container with for example an its_alive via http
      exit 0
    else
      VERSION=$old_version
      stop server
      stop daemon
      if container_exists wispro-server; then
        docker container rm wispro-server
      fi
      docker container rename wispro-server-bak wispro-server
      if container_exists wispro-daemon; then
        docker container rm wispro-daemon
      fi
      docker container rename wispro-daemon-bak wispro-daemon
      cp $db_path.bak ${db_path}
      start server
      start daemon
      echo "Upgrade to version ${new_version} failed."
      exit 1
    fi
  else
    echo "Upgrade to version ${new_version} failed."
    exit 1
  fi
  ;;
console)
  docker exec -it wispro-server /bin/bash -c "rails c"
  ;;
log)
  tail -n500 -F /usr/src/app/log/application.log
  ;;
apply)
  docker exec -it wispro-server /bin/bash -c "rails runner 'ApplyChanges.new.boot'"
  ;;
bash-server)
  docker exec -it wispro-server /bin/bash
  ;;
bash-daemon)
  docker exec -it wispro-daemon /bin/bash
  ;;
reset)
  echo "Deleting all containers and Wispro database, are you sure?"
  echo "(Pres Ctrl-c to cancel/Enter to continue)"
  read dummy
  VERSION=$(docker inspect --format='{{.Config.Image}}' wispro-server | awk -F: '{print $2}')
  stop server
  stop daemon
  docker container prune -f
  start server
  start daemon
  #rm -f /usr/src/app/data/wispro_bmu_production.sqlite3
  ;;
top)
  echo
  echo "Wispro Server"
  docker top wispro-server
  echo
  echo "Wispro Daemon"
  docker top wispro-daemon
  ;;
*)
  echo "error - wrong arguments"
  ;;
esac
